sudo: true
os: linux
cache: false

env:
- URL=https://appiriodx-website-prod.s3.amazonaws.com/downloads/adx-cli-linux.tar.gz

before_install:
- mkdir sfdx
- wget $URL
- tar -xzf adx-cli-linux.tar.gz
- pwd
- ls

script:
- adx --version
