sudo: true
os: linux
cache: false

env:
- URL=https://appiriodx-website-prod.s3.amazonaws.com/downloads/adx-cli-linux.tar.gz

before_install:
- mkdir adx
- wget $URL
- tar -xzf adx-cli-linux.tar.gz
- "./adx/install"
- pwd
- ls
- export PATH=./adx/$(pwd):$PATH

script:
- adx --version
