sudo: true
os: linux
cache: false
language: generic

env:
- URL=https://appiriodx-website-prod.s3.amazonaws.com/downloads/adx-cli-linux.tar.gz

before_install:
- mkdir adx
- cd adx
- wget $URL
- tar xzf adx-cli-linux.tar.gz
- pwd
- ls
- env
- export PATH=$(pwd):$PATH

script:
- adx
