sudo: true
os: linux
cache: false
language: generic

git:
  depth: false
  
stages:
  - lint
  - build
  - test

jobs:
  include:
      - stage: lint
        script: echo 'lint'
      - stage: build
        script:
          - echo 'build'
      - stage: test
        script: echo 'test'
  
